# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-2019
    
    strategy:
      matrix:
        platform: [win32, x64]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: true
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /t:rebuild /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{matrix.platform}} /v:diag  ${{env.SOLUTION_FILE_PATH}}
      
    - name: Attest provenance
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'bin\${{matrix.platform}}\${{env.BUILD_CONFIGURATION}}\*.dll'
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: oxrmc-binary-(${{matrix.platform}})
        path: |
          bin\${{matrix.platform}}\${{env.BUILD_CONFIGURATION}}\*.dll
          bin\${{matrix.platform}}\${{env.BUILD_CONFIGURATION}}\MmfReader\*.exe
        
  merge:
    runs-on: windows-2019
    needs: build
    outputs:
      artifact-id: ${{ steps.artifact-merge-step.outputs.artifact-id }}
    
    steps:
    - name: Merge artifacts
      uses: actions/upload-artifact/merge@v4
      id: artifact-merge-step
      with:
        name: oxrmc-binaries
        delete-merged: true
      
  sign:
    runs-on: windows-2019
    needs: merge
    
    steps:
    - name: Request SignPath signature
      uses: signpath/github-action-submit-signing-request@v0.4
      with:
        api-token: ${{secrets.APPVEYOR_API_TOKEN}}
        organization-id: 11e4bc12-01ae-4f8c-8c5f-233747e24ab1
        project-slug: OpenXR-MotionCompensation
        signing-policy-slug: test-signing
        github-artifact-id: ${{needs.merge.outputs.artifact-id}}
        wait-for-completion: true